let names = [
  "Ivory Coast",
  "Ghana",
  "Ethiopia",
  "Algeria",
  "Eritrea",
  "Mali",
  "Central African Republic",
  "Gambia",
  "Guinea-Bissau",
  "Malawi",
  "Republic of the Congo",
  "Burundi",
  "Egypt",
  "Morocco",
  "Spain",
  "Guinea",
  "Senegal",
  "Tanzania",
  "Djibouti",
  "Cameroon",
  "Morocco",
  "Sierra Leone",
  "Botswana",
  "Zimbabwe",
  "South Africa",
  "South Sudan",
  "Uganda",
  "Sudan",
  "Rwanda",
  "Democratic Republic of the Congo",
  "Nigeria",
  "Gabon",
  "Togo",
  "Angola",
  "Democratic Republic of the Congo",
  "Zambia",
  "Equatorial Guinea",
  "Mozambique",
  "Lesotho",
  "Eswatini",
  "Somalia",
  "Liberia",
  "Kenya",
  "Chad",
  "Niger",
  "Mauritania",
  "Burkina Faso",
  "Benin",
  "Sao Tome and Principe",
  "Libya",
  "Tunisia",
  "Namibia",
  "United States",
  "United States",
  "Anguilla",
  "Antigua and Barbuda",
  "Brazil",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Argentina",
  "Aruba",
  "Paraguay",
  "Canada",
  "Brazil",
  "Mexico",
  "Barbados",
  "Brazil",
  "Belize",
  "Canada",
  "Brazil",
  "Colombia",
  "United States",
  "Canada",
  "Brazil",
  "Mexico",
  "Venezuela",
  "French Guiana",
  "Cayman Islands",
  "United States",
  "Mexico",
  "Costa Rica",
  "Canada",
  "Brazil",
  "Curacao",
  "Greenland",
  "Canada",
  "Canada",
  "United States",
  "United States",
  "Dominica",
  "Canada",
  "Brazil",
  "El Salvador",
  "Canada",
  "Brazil",
  "Canada",
  "Canada",
  "Turks and Caicos Islands",
  "Grenada",
  "Guadeloupe",
  "Guatemala",
  "Ecuador",
  "Guyana",
  "Canada",
  "Cuba",
  "Mexico",
  "United States",
  "United States",
  "United States",
  "United States",
  "United States",
  "United States",
  "United States",
  "United States",
  "Canada",
  "Canada",
  "Jamaica",
  "United States",
  "United States",
  "United States",
  "Bonaire, Saint Eustatius and Saba",
  "Bolivia",
  "Peru",
  "United States",
  "Sint Maarten",
  "Brazil",
  "Nicaragua",
  "Brazil",
  "Saint Martin",
  "Martinique",
  "Mexico",
  "Mexico",
  "United States",
  "Mexico",
  "United States",
  "Mexico",
  "Saint Pierre and Miquelon",
  "Canada",
  "Mexico",
  "Uruguay",
  "Montserrat",
  "Bahamas",
  "United States",
  "United States",
  "Brazil",
  "United States",
  "United States",
  "United States",
  "Greenland",
  "Mexico",
  "Panama",
  "Canada",
  "Suriname",
  "United States",
  "Haiti",
  "Trinidad and Tobago",
  "Brazil",
  "Puerto Rico",
  "Chile",
  "Canada",
  "Brazil",
  "Canada",
  "Canada",
  "Brazil",
  "Brazil",
  "Chile",
  "Dominican Republic",
  "Brazil",
  "Greenland",
  "United States",
  "Saint Barthelemy",
  "Canada",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "U.S. Virgin Islands",
  "Saint Vincent and the Grenadines",
  "Canada",
  "Honduras",
  "Greenland",
  "Mexico",
  "Canada",
  "British Virgin Islands",
  "Canada",
  "Canada",
  "Canada",
  "United States",
  "Canada",
  "Antarctica",
  "Antarctica",
  "Antarctica",
  "Australia",
  "Antarctica",
  "Antarctica",
  "Antarctica",
  "Antarctica",
  "Antarctica",
  "Antarctica",
  "Antarctica",
  "Svalbard and Jan Mayen",
  "Yemen",
  "Kazakhstan",
  "Jordan",
  "Russia",
  "Kazakhstan",
  "Kazakhstan",
  "Turkmenistan",
  "Kazakhstan",
  "Iraq",
  "Bahrain",
  "Azerbaijan",
  "Thailand",
  "Russia",
  "Lebanon",
  "Kyrgyzstan",
  "Brunei",
  "Russia",
  "Mongolia",
  "Sri Lanka",
  "Syria",
  "Bangladesh",
  "Timor Leste",
  "United Arab Emirates",
  "Tajikistan",
  "Cyprus",
  "Palestinian Territory",
  "Palestinian Territory",
  "Vietnam",
  "Hong Kong",
  "Mongolia",
  "Russia",
  "Indonesia",
  "Indonesia",
  "Israel",
  "Afghanistan",
  "Russia",
  "Pakistan",
  "Nepal",
  "Russia",
  "India",
  "Russia",
  "Malaysia",
  "Malaysia",
  "Kuwait",
  "Macao",
  "Russia",
  "Indonesia",
  "Philippines",
  "Oman",
  "Cyprus",
  "Russia",
  "Russia",
  "Russia",
  "Kazakhstan",
  "Cambodia",
  "Indonesia",
  "North Korea",
  "Qatar",
  "Kazakhstan",
  "Kazakhstan",
  "Saudi Arabia",
  "Russia",
  "Uzbekistan",
  "South Korea",
  "China",
  "Singapore",
  "Russia",
  "Taiwan",
  "Uzbekistan",
  "Georgia",
  "Iran",
  "Bhutan",
  "Japan",
  "Russia",
  "Mongolia",
  "China",
  "Russia",
  "Laos",
  "Russia",
  "Russia",
  "Myanmar",
  "Russia",
  "Armenia",
  "Portugal",
  "Bermuda",
  "Spain",
  "Cabo Verde",
  "Faroe Islands",
  "Portugal",
  "Iceland",
  "South Georgia and the South Sandwich Islands",
  "Saint Helena",
  "Falkland Islands",
  "Australia",
  "Australia",
  "Australia",
  "Australia",
  "Australia",
  "Australia",
  "Australia",
  "Australia",
  "Australia",
  "Australia",
  "Australia",
  "Netherlands",
  "Andorra",
  "Russia",
  "Greece",
  "Serbia",
  "Germany",
  "Slovakia",
  "Belgium",
  "Romania",
  "Hungary",
  "Germany",
  "Moldova",
  "Denmark",
  "Ireland",
  "Gibraltar",
  "Guernsey",
  "Finland",
  "Isle of Man",
  "Turkey",
  "Jersey",
  "Russia",
  "Russia",
  "Ukraine",
  "Portugal",
  "Slovenia",
  "United Kingdom",
  "Luxembourg",
  "Spain",
  "Malta",
  "Aland Islands",
  "Belarus",
  "Monaco",
  "Russia",
  "Norway",
  "France",
  "Montenegro",
  "Czechia",
  "Latvia",
  "Italy",
  "Russia",
  "San Marino",
  "Bosnia and Herzegovina",
  "Russia",
  "Ukraine",
  "North Macedonia",
  "Bulgaria",
  "Sweden",
  "Estonia",
  "Albania",
  "Russia",
  "Liechtenstein",
  "Vatican",
  "Austria",
  "Lithuania",
  "Russia",
  "Poland",
  "Croatia",
  "Switzerland",
  "Madagascar",
  "British Indian Ocean Territory",
  "Christmas Island",
  "Cocos Islands",
  "Comoros",
  "French Southern Territories",
  "Seychelles",
  "Maldives",
  "Mauritius",
  "Mayotte",
  "Reunion",
  "Samoa",
  "New Zealand",
  "Papua New Guinea",
  "New Zealand",
  "Micronesia",
  "Chile",
  "Vanuatu",
  "Tokelau",
  "Fiji",
  "Tuvalu",
  "Ecuador",
  "French Polynesia",
  "Solomon Islands",
  "Guam",
  "United States",
  "Kiribati",
  "Kiribati",
  "Micronesia",
  "Marshall Islands",
  "Marshall Islands",
  "French Polynesia",
  "United States Minor Outlying Islands",
  "Nauru",
  "Niue",
  "Norfolk Island",
  "New Caledonia",
  "American Samoa",
  "Palau",
  "Pitcairn",
  "Micronesia",
  "Papua New Guinea",
  "Cook Islands",
  "Northern Mariana Islands",
  "French Polynesia",
  "Kiribati",
  "Tonga",
  "United States Minor Outlying Islands",
  "Wallis and Futuna",
];

let sortedNames = names.sort();
let input = document.getElementById("input");
function titleCase(str) {
  let words = str.toLowerCase().split(" ");
  for (let i = 0; i < words.length; i++) {
    words[i] = words[i][0].toUpperCase() + words[i].slice(1);
  }
  return words.join(" ");
}

input.addEventListener("keyup", (e) => {
    removeElements();
  for (let i of sortedNames) {
    if (
      titleCase(i).startsWith(titleCase(input.value)) &&
      input.value != ""
    ) {
      let listItem = document.createElement("li");
      listItem.classList.add("list-items");
      listItem.style.counter = "pointer";
      listItem.setAttribute("onclick", "displayNames('" + i + "')");
      let word = "<b>" + i.substring(0, input.value.length) + "</b>";
      word += i.substring(input.value.length);
      listItem.innerHTML = word;
      document.querySelector(".list").appendChild(listItem);

    }
  }
});
function displayNames(value){
    input.value = value;
    removeElements();
}
function removeElements(){
    let itemss = document.querySelectorAll(".list-items");
    itemss.forEach((item) =>{
        item.remove();
    } );
}